//
//  Data.swift
//  SwiftUI-MotoGP
//
//  Created by 07 Zhang on 2020/3/21.
//  Copyright © 2020 07 Zhang. All rights reserved.
//

import Foundation

let Rider=[
    Riders(Name:"Valentino Rossi-瓦倫蒂諾·羅西",Bikenumber:"46",Championships:"7\n(2001.2002. 2003.2004.2005.2008.2009)",Team:"Monster Energy Yamaha MotoGP",Manufacturers: "Yamaha",Age: "41",Nationality: "義大利Italian",Activeyears: "(2000~至今)",Introduction: "     世界摩托車錦標賽車手，1979年2月16日出生於義大利塔武利亞，他的父親格拉齊亞諾·羅西(Graziano Rossi)也曾是GP大獎賽的車手(1977-1982)。\n\n     目前隸屬Monster Energy Yamaha，從1996年加入世界摩托車錦標賽，獲得全部級別9座世界冠軍，由於參賽以來成績優異有「小飛俠」與「猴王」的暱稱。\n\n       有一代人看MotoGP，是伴著羅西一起過來的。就如同當年喬丹就意味著NBA一樣，羅西在很多車友眼裡就是MotoGP的代名詞。\n\n      羅西在WGP賽場上的第二年就表現的遊刃有餘。他繼續駕駛阿普利亞125戰車，過關斬將，切菜劈瓜般全年共拿下11個分站冠軍，以321分的總成績獲得年度冠軍，成為WGP歷史上第二位最年輕的125cc組世界冠軍！2002年，世界摩托車大獎賽改變規則，兩沖時代結束，WGP變成了MotoGP。\n\n       23歲的羅西駕駛著全新的四衝程本田RC211V賽車，繼續統治賽場，以355分和11個分站冠軍的成績獲得年度總冠軍，成為史上第一位MotoGP世界冠軍。\n\n     羅西（Rossi）被公認為有史以來最偉大的摩托車賽車手之一，以他的名字參加了9次世界大獎賽，其中有7次是頂級比賽。羅西（Rossi）也是唯一參加過400場或更多大獎賽的公路賽車手。\n\n      在成為冠軍時，他整個職業生涯都使用了46號。\nMotoGP起跑次數    342次\nMotoGP分站冠軍(第一名)次數    89次\nMotoGP頒獎台次數    198次\nMotoGP杆位(第一位置起跑)    55次\n看到其在各項摩托車賽事的成績，造就其為摩托車賽事的指標性人物。\n\n      補充：常見的ＡＧＶ彩繪-46安全帽\n\n\n\n\n\n"),
    Riders(Name:"Marc Márquez-馬克·馬奎斯",Bikenumber:"93",Championships:"6\n(2013.2014.2016.2017.2018.2019）",Team:"Repsol Honda Team",Manufacturers: "Honda",Age: "27",Nationality: "西班牙Spanish",Activeyears: "(2008~至今)",Introduction: "     一名西班牙籍的世界摩托車錦標賽賽車手，截至2019年為止已奪得全部級別八座世界冠軍。\n\n      1993年2月17日出生於西班牙，從小父親便栽培其成為一位賽車手。目前隸屬於本田廠隊 Repsol Honda Team。馬奎斯曾連續奪得MotoGP六屆世界冠軍，實力非凡，同時他也是65年的MotoGP歷史中，備受矚目的超級新星，其他三位是邁克·海爾伍德、菲爾·瑞德和瓦倫蒂諾·羅西!\n\n     馬奎斯於2010年取得125c.c.級別的世界冠軍，並在2012年取得Moto2級別的世界冠軍，2013年升為MotoGP選手並以新秀之姿奪得摩托車界賽車殿堂最高榮耀：MotoGP世界冠軍，成為GP史上最年輕的世界冠軍，而該年更創下許多紀錄。\n\n       翌年2014年開季即拿下十連勝，到了第11站Brno連勝紀錄才被隊友丹尼·佩卓沙停止，後於該年第15站茂木賽道的比賽中奪得第二名並提前奪得MotoGP世界冠軍，該年亦寫下多項紀錄。\n\n      2015年馬奎斯的賽季並不順利，總計有6次的DNF（未完賽），並於賽季尾聲與瓦倫蒂諾·羅西發生衝突引發媒體及社群網站大肆討論，該年馬奎斯以年度第三名作收。\n\n       被外界喻為下一個瓦倫蒂諾·羅西。\n\n        其胞弟Álex Márquez也是世界摩托車錦標賽賽車手，現在為MotoGP級別的選手。\n\n      補充：2019賽季獲得最高420分的積分成績。\n           常見的ＳＨＯＥＩ-93安全帽\n\n\n\n\n\n"),
    
    
    
    Riders(Name:"Andrea Dovizioso-安德列·多維茲奧索",Bikenumber:"04",Championships:"0",Team:"Mission Winnow Ducati Team",Manufacturers: "Ducati",Age: "34",Nationality: "義大利Italian",Activeyears: "(2008~至今)",Introduction: "     專業的摩托車賽車手，他為MotoGP Ducati Corse車隊爭奪世界冠軍。\n\n      他在2004年贏得了125cc世錦賽冠軍。他在2011年的MotoGP比賽中也獲得了第三名，並且在2017年、2018年和2019年僅次於MarcMárquez奪得了亞軍之後，近幾年最接近冠軍的男人，曾在各級別三次獲得世界冠軍。\n\n     2019賽季，Dovizioso連續第二次獲得卡塔爾（Qatar）大獎賽冠軍，並在紅牛圈（Red Bull Ring）贏得奧地利大獎賽的冠軍。\n\n     他在英國大獎賽上遭遇了一次大事故，當時他無法避免將法國車手(Fabio Quartararo)法比奧·誇塔拉羅撞倒在他面前，且撞上了機車，使他空降下來並由頭撞向地面。 事故使他暫時失去了記憶力，之後完全康復。\n\n     2019賽季他獲得了9次登上領獎台，這與2018賽季的成績相當。 Dovizioso以269分的最高成績獲得了自己迄今為止的最高職業成績，這是他連續第三個賽季排名第二\n\n      補充：2018年騎著Ducati賽車在義大利分站創造了MotoGP最高速度356.4km/h (221.5 mph)，簡單比喻～相當於臺灣高鐵的時速\n\n\n\n\n\n"),
    
    Riders(Name:"Johann Zarco-約翰·薩爾科",Bikenumber:"05",Championships:"0",Team:"Reale Avintia Racing(Ducati)",Manufacturers: "Ducati",Age: "29",Nationality: "法國French",Activeyears: "(2017~至今)",Introduction: "     是法國世界摩托車錦標賽車手，贏得2015年和2016年的 Moto2世界冠軍而聞名。\n\n      從2017年開始，他成為Tech 3 Yamaha MotoGP衛星團隊的成員，並於2018年初宣布，他將從2019年開始效力於工廠KTM MotoGP團隊。\n\n     在2019年8月，Zarco宣布他將在合同的第二年2020年不參加KTM廠隊。然後，KTM團隊於2019年9月宣布，他將不再參加2019年的其餘六項賽事，而測試車手Mika Kallio將取代他的位置。\n\n     在經歷了艱難的2019賽季之後，Zarco與Avintia Ducati簽訂了2020年與MotoGP簽約的合約。\n\n     Zarco贏得了16項大獎賽冠軍，也是法國大獎賽中最成功的法國車手。\n\n      在MotoGP級別也多次站上分站賽的頒獎台，其實力也是不可忽視。\n\n\n\n\n\n"),
    
    Riders(Name:"Danilo PetrucciRiders-達尼洛·佩特魯奇",Bikenumber:"09",Championships:"0",Team:"Mission Winnow Ducati Team",Manufacturers: "Ducati",Age: "29",Nationality: "義大利Italian",Activeyears: "(2012~至今)",Introduction: "      是意大利世界摩托車錦標賽車手，他曾經在2011年贏得了意大利Superstock 1000錦標賽冠軍，目前為Ducati Corse車隊參加MotoGP世界冠軍。\n\n       在去年的義大利分站獲得了第一名，拿到在MotoGP的第一座優勝獎杯，目前生涯已獲得9次站上頒獎台的成績。另外，在去年的騎乘表現、實力與同隊的Andrea Dovizioso相當。\n\n\n\n\n\n"),
    Riders(Name:"Maverick Viñales-馬維里克·維那勒斯",Bikenumber:"12",Championships:"0",Team:"Monster Energy Yamaha MotoGP",Manufacturers: "Yamaha",Age: "25",Nationality: "西班牙Spanish",Activeyears: "(2015~至今)",Introduction: "        是西班牙世界摩托車錦標賽的摩托車手，曾於2013年獲得Moto3世界冠軍。\n\n       他目前正在參加MotoGP的頂級比賽，在2015年他贏得了MotoGP的年度最佳新人稱號。\n\n       2015年賽季Viñales與賽車鈴木車廠(Suzuki)。對於這家日本製造商來說，這是復出的一年，他們獲得了各種開發方面的進步，並且在賽季中對賽車進行了幾處改動。Viñales完成了18場比賽中的16場，一路拿下6項前10名成績，這再次證明了他的實力。積分當中他以第12位結束賽季，贏得了年度最佳新人獎。\n\n       生涯目前有7次第一名獲勝與總計23次頒獎台，在去年賽季積分為第三名。目前與Rossi為同車廠的隊友\n\n\n\n\n\n"),
    Riders(Name:"Fabio Quartararo-法比奧·誇塔拉羅",Bikenumber:"20",Championships:"0",Team:"Petronas Yamaha SRT",Manufacturers: "Yamaha",Age: "25",Nationality: "法國French",Activeyears: "(2019~至今)",Introduction: "        是法國世界摩托車錦標賽的摩托車手，2015年賽季16歲時參加了Moto3級別的賽事，參與了兩年的Moto3賽事，並在2017年晉升至Moto2級別，同樣征戰兩年，雖然成績並不亮眼，但其潛在的實力被廠隊Petronas Yamaha SRT相中，在2019年賽季邀請到最高級別的MotoGP賽場上。\n\n     在大獎賽生涯之前，Quartararo贏得了六個西班牙冠軍頭銜，包括在2013年和2014年連續獲得CEV Moto3(青年Moto3錦標賽)冠軍頭銜。\n\n        在MotoGP的第一年就獲得了7次的頒獎台，和6次的杆位(第一位置起跑)，並獲得2019年MotoGP年度最佳新人獎。\n\n     由於年輕時的成功，被與目前多個世界冠軍Marc Márquez進行了比較，並且在晉級MotoGP級別的過程中打破了多項年齡記錄水平。\n\n\n\n\n\n"),
    Riders(Name:"Franco Morbidelli-佛朗哥·莫比德利",Bikenumber:"21",Championships:"0",Team:"Petronas Yamaha SRT",Manufacturers: "Yamaha",Age: "25",Nationality: "義大利Italian",Activeyears: "(2018~至今)",Introduction: "        是意大利世界摩托車錦標賽車手，2013年歐洲Superstock 600冠軍，且在2017年於Marc VDS Racing Team廠隊贏得Moto2的世界冠軍。\n\n        2017賽季獲得8次分站冠軍，生涯總計21次頒獎台。\n\n        在2013-2017年在Moto2級別的賽事上表現優異，晉升為MotoGP級別，目前在MotoGP仍在不斷努力。與Fabio Quartararo是同隊隊友。\n\n\n\n\n\n"),
    Riders(Name:"Iker Lecuona-伊克·勒庫奧納",Bikenumber:"27",Championships:"0",Team:"Red Bull KTM Tech 3",Manufacturers: "KTM",Age: "20",Nationality: "西班牙Spanish",Activeyears: "(2019~至今)",Introduction: "        MotoGP西班牙的新人賽車手，原先是Moto2的賽車手，在2016 Lecuona他的首場比賽Moto2世界錦標賽替代受傷的多米尼克·阿格特在CarXpert Interwetten廠隊的兩場比賽;在本賽季晚些時候，他重新加入車隊，成為替代的車手，接續下年度的比賽。\n\n        在赫雷斯-安赫爾·涅托賽道進行季前測試時，他在一次撞車事故中嚴重傷及背部和鎖骨，並缺席了2017賽季的前兩場比賽。\n\n       2019年11月7日，宣布他將參加MotoGP比賽2019賽季的最後一場大獎賽，Valencian Community賽道大獎賽，以取代受傷的Miguel Oliveira。\n\n\n\n\n\n"),
    Riders(Name:"Andrea Iannone-安德里亞·亞農",Bikenumber:"29",Championships:"0",Team:"Aprilia Racing Team Gresini",Manufacturers: "Aprilia",Age: "30",Nationality: "義大利Italian",Activeyears: "(2013~至今)",Introduction: "        義大利的賽車手，自從15歲時就開始挑戰125cc級別的賽事，分別參加過125cc、Moto2、MotoGP的賽事，在多年的騎乘之下，累積了許多的經驗。\n\n     在各級別的賽事中皆有拿下亮麗的成績，無論是分站第一名獲勝或是頒獎台，曾在Moto2級別中獲得賽季的第三名積分成績。\n\n       雖然目前仍未在MotoGP中拿下年度冠軍，但是在比賽中的騎乘技巧與反應能力也是值得關注的焦點。\n\n     不幸的是去年賽季末在經過藥物測試後，Iannone於2019年12月被暫時停止摩托車比賽。確定會在本年度回歸比賽。\n\n\n\n\n\n"),
    Riders(Name:"Nakagami Takaaki-中上貴晶",Bikenumber:"30",Championships:"0",Team:"LCR Honda IDEMITSU",Manufacturers: "Honda",Age: "28",Nationality: "日本Japanese",Activeyears: "(2018~至今)",Introduction: "       日本的賽車手，目前唯一的亞洲籍賽車手，是日本地區的職業賽車手，在2006年贏得了日本GP125冠軍、在2010年鈴鹿8小時賽事與團隊騎乘CBR1000RRW獲得第一名。\n\n        同樣分別參加過125cc、Moto2、MotoGP的賽事，在Moto2的表現亮眼，2次的第一名獲勝與14次的分站頒獎台。\n\n        Nakagami 於2018年晉升為MotoGP，與創立第一年的LCR車隊簽約。在2018年10月，證實中上將與隊友Cal Crutchlow一起留在LCR本田車隊參加2019年MotoGP賽季。2020也繼續與同廠隊參加MotoGP賽事。\n\n\n\n\n\n"),
    Riders(Name:"Brad Binder-布拉德·賓德",Bikenumber:"33",Championships:"0",Team:"Red Bull KTM Factory Racing",Manufacturers: "KTM",Age: "24",Nationality: "南非South African",Activeyears: "(2020~至今)",Introduction: "       來自南非的世界摩托車錦標賽摩托車手。在2019年11月，他被確認為2020賽季MotoGP級別的Red Bull KTM Factory Racing車手，代替了今年初取消與此廠隊合作的Johann Zarco-約翰·薩爾科。\n\n        曾在2019年與KTM satellite team Tech3場隊一起參加Moto2比賽，獲得年度積分第二名。\n\n        他還以贏得2016年Moto3世界冠軍而聞名。在晉級MotoGP之前，Binder參加了紅牛MotoGP新秀杯三個賽季的比賽，總成績排名第五。\n\n     在南非赫雷斯舉行的西班牙摩托車大獎賽上的第一個贏得摩托車大獎賽的南非人。\n\n        在Moto3及Moto2兩級別的成績亮眼，多次分站冠軍與頒獎台，在今年晉升MotoGP是值得關注的新人。\n\n\n\n\n\n"),
    Riders(Name:"Cal Crutchlow-卡爾·克勞奇洛",Bikenumber:"35",Championships:"0",Team:"LCR Honda CASTROL",Manufacturers: "Honda",Age: "34",Nationality: "英國British",Activeyears: "(2011~至今)",Introduction: "       英國的專業摩托車公路賽車手，曾為LCR車隊參加MotoGP世界錦標賽。\n\n     2017年初，RAC(皇家汽車俱樂部)授予Crutchlow Torrens獎杯，該獎項是對“對英國摩托車的傑出貢獻”的認可。\n\n     他的職業生涯始於Superbike World Championship。他騎乘Yamaha車廠贏得2006年的英國超級運動錦標賽冠軍和2009年Supersport World Championship冠軍。\n\n       他還贏得了英國超級摩托車錦標賽的比賽（2008年獲得第三名）和超級摩托車世界錦標賽的比賽（2010年獲得第五名）。\n\n       自2011年以來，Crutchlow參加了MotoGP世界錦標賽。他加入了Tech 3 Yamaha衛星團隊，在2011年至2013年的三個賽季中完成了六次領獎台。\n\n      在2014年，Crutchlow加盟factory Ducati team為期兩年的合同。登上一次領獎台，並在賽季結束積分總結第13名。\n\n        -僅僅一個賽季後，Ducati廠隊Crutchlow終止了他的合約。2015年賽季之後到目前都於LCR Honda CASTROL，騎乘Honda廠隊的賽車。\n\n\n\n\n\n"),
    Riders(Name:"Joan Mir-瓊·米爾",Bikenumber:"36",Championships:"0",Team:"Team SUZUKI ECSTAR",Manufacturers: "Suzuki",Age: "22",Nationality: "西班牙Spanish",Activeyears: "(2019~至今)",Introduction: "       是西班牙世界摩托車錦標賽的摩托車手，Mir過去參加Red Bull MotoGP新秀杯和CEV Moto3錦標賽的賽車手。\n\n        並且他和廠隊Leopard Racing贏得了2017年Moto3世界冠軍。\n\n      2017年Moto3賽事總共獲得10次的分站冠軍(第一名)。\n\n        2018年在與車隊和HRC簽定了四年合約之後，Mir與Marc VDS Racing Team一起參加了Moto2級別。\n\n        2019則與Suzuki廠隊進入MotoGP賽事。\n\n\n\n\n\n"),
    Riders(Name:"Aleix Espargaró",Bikenumber:"41",Championships:"0",Team:"Aprilia Racing Team Gresini",Manufacturers: "Aprilia",Age: "30",Nationality: "西班牙Spanish",Activeyears: "(2009~2010、2012~至今)",Introduction: "       Aleix Espargaró-阿萊克斯·埃斯帕爾加羅，西班牙世界摩托車錦標賽的摩托車手，2009年10月6日，宣布Espargaró與Pramac Ducati簽署了參加2010年MotoGP冠軍賽事的合約。他替換了隊中的NiccolòCanepa。在2009年雪邦和瓦倫西亞的最後兩站比賽中，他替換了受傷的Canepa。\n\n       在2011年回到Moto2後，Espargaro回到了MotoGP賽事，並且是2012和2013賽季CRT車手排名最高的車手。\n\n     2014年，他參加了第150項賽事，這是他在荷蘭TT賽上首次獲得杆位。在賽季結束後，他簽約了鈴木工廠的車隊，從2015年開始騎乘新的Suzuki-GSX-RR。\n\n        自2017年以來，正式為Aprilia廠隊的車手。\n\n      他的弟弟波爾（Pol Espargaró）也是世界摩托車錦標賽的車手，曾經與阿萊克斯同樣參加在2011年的Moto2比賽。\n\n\n\n\n\n"),
    Riders(Name:"Álex Rins-亞歷克斯·里斯",Bikenumber:"42",Championships:"0",Team:"Team SUZUKI ECSTAR",Manufacturers: "Suzuki",Age: "24",Nationality: "西班牙Spanish",Activeyears: "(2017~至今)",Introduction: "       西班牙世界摩托車錦標賽的摩托車手，他在2012賽季的Moto3世界錦標賽上首次亮相。\n\n       Rins是2011年西班牙125GP系列冠軍（SIC）和2019年美洲大獎賽的冠軍。\n\n      分別在2014年與2016拿下Moto3與Moto2的年度積分度三名。\n\n     2017年賽季晉升為MotoGP級別賽事，騎乘Suzuki廠隊的賽車。\n\n     2019年賽季在卡塔爾分站和阿根廷分站獲得了領獎台成績之後，贏得了2019年美洲大獎分站賽，而馬克·馬奎茲（MarcMárquez）不幸退賽後與瓦倫蒂諾·羅西（Valentino Rossi）決鬥爭奪第一名位置。這是他在MotoGP級別的第一場勝利和鈴木的第一場勝利。\n\n     Rins以205分的成績結束了本賽季的比賽，這使他在錦標賽中積分排名第四，這是迄今為止他最好的MotoGP賽季。\n\n     補充： 2019英國分站時，在“最後一圈”的“最後一個彎道”，超掉了當時第一名領跑的馬克·馬奎茲（MarcMárquez）獲得了第一名，成為了整場比賽的精華，堅強的意志讓他在最後一刻看見了獲勝的契機，提早煞車、進入彎道、把握最內側的路線，出了彎之後加速衝過終點，以此奪下了分站冠軍。\n\n\n\n\n\n"),
    Riders(Name:"Jack Miller-傑克·米勒",Bikenumber:"43",Championships:"0",Team:"Alma Pramac Racing",Manufacturers: "Ducati",Age: "25",Nationality: "澳洲Australian",Activeyears: "(2015~至今)",Introduction: "       澳大利亞世界摩托車錦標賽的摩托車手，以在2014年Moto3世界錦標賽上獲得積分第二名而聞名。他是2011年德國IDM 125cc冠軍。目前MotoGP唯一的澳洲車手。\n\n       2011年是他在歐洲取得突破的一年。一連串的強勁表現使他在16歲時贏得了德國IDM 125cc類別的冠軍，這一成績贏得了意大利名車隊Caretta Technology的Forward Racing的注意，與Miller簽約參加了2012年Moto3冠軍賽。\n\n       曾合作的廠隊有LCR團隊（2015）、Marc VDS賽車隊（2016–2017）、Pramac Racing（2018年至今），2019年賽季獲得5次頒獎台的殊榮。\n\n\n\n\n\n"),
    Riders(Name:"Pol Espargaró-波爾·埃斯帕爾加羅",Bikenumber:"44",Championships:"0",Team:"Red Bull KTM Factory Racing",Manufacturers: "KTM",Age: "28",Nationality: "西班牙Spanish",Activeyears: "(2014~至今)",Introduction: "       西班牙世界摩托車錦標賽的摩托車手，Pol是Aleix Espargaró的弟弟，Pol以贏得2013年 Moto2世界冠軍而聞名。\n\n        他在2015年與布拉德利·史密斯（Bradley Smith）和中春克幸（Katsuyuki Nakasuga）一起贏得了鈴鹿8小時耐力賽，並在2016年與（Nakasuga）和亞歷克斯·洛斯（Alex Lowes）一起贏得了“ 鈴鹿8小時”。\n\n       他是第一個在MotoGP 上駕駛KTM摩托車登上領獎台的賽車手。\n\n        在Moto2級別時期，多次獲得分站冠軍，於2013年積分排名第一，為當年的冠軍。\n\n        2014晉升為MotoGP賽事，前兩年與Tech 3 satellite Yamaha racing team廠隊合作，2017年至今與KTM廠隊合作，騎乘KTM的賽車。\n\n\n\n\n\n"),
    Riders(Name:"Tito Rabat-鐵托·拉巴特",Bikenumber:"53",Championships:"0",Team:"Reale Avintia Racing",Manufacturers: "Ducati",Age: "30",Nationality: "西班牙Spanish",Activeyears: "(2016~至今)",Introduction: "       西班牙世界摩托車錦標賽的摩托車手，他以贏得2014年Moto2世界冠軍而著稱，車手的總積分刷新紀錄(346分)。\n\n     拉巴特（Rabat）於2018年8月嚴重腿部受傷，在大雨中摔落在英國銀石賽道（Silverstone），他被失控的賽車擊中所受傷。\n\n       曾在Moto2級別中，於2013、2015獲得年度積分第三名，2014年7次分站冠軍，且獲得346分積分成績，成為當年度的冠軍車手。\n\n\n\n\n\n"),
    Riders(Name:"Francesco Bagnaia",Bikenumber:"63",Championships:"0",Team:"Alma Pramac Racing",Manufacturers: "Ducati",Age: "23",Nationality: "義大利Italian",Activeyears: "(2019~至今)",Introduction: "       Francesco Bagnaia-弗朗切斯科·巴格尼亞，義大利世界摩托車錦標賽的摩托車手，他是2018年Moto2世界冠軍。\n\n     在2018的Moto2級別在賽季中獲勝8場比賽後：Losail，美洲賽道，勒芒，阿森，紅牛賽道，米薩諾，布里蘭和茂木賽道，完成本賽季共有12次登上領獎台，6個杆位和積分306點，成為年度冠軍。\n\n      2019年晉升MotoGP賽事。\n\n        在澳大利亞的菲利普島賽道，巴格尼亞以第四名的身份結束比賽，僅以0.055秒的成績落後隊友傑克·米勒（Jack Miller）錯過了領獎台。\n\n\n\n\n\n"),
    Riders(Name:"Álex Márquez-亞歷克斯·馬奎斯",Bikenumber:"73",Championships:"0",Team:"Repsol Honda Team",Manufacturers: "Honda",Age: "23",Nationality: "西班牙Spanish",Activeyears: "(2020~至今)",Introduction: "       西班牙世界摩托車錦標賽的摩托車手，他是2019年Moto2世界冠軍，在2019年獲得5次的分站冠軍。\n\n     對於2020賽季，Alex將與他的兄弟Marc Márquez一起加入Repsol本田車隊，接替在2019年MotoGP賽季結束時退休的豪爾赫·洛倫佐(Jorge Lorenzo)。Álex Márquez意外地從Moto2晉升為MotoGP，另外在2019年11月勞倫斯（Lorenzo）宣布退役後，他仍在2020年與Marc VDS簽約。\n\n        和其兄弟Marc Márquez在去年分別為Moto2與MotoGP年度冠軍，也會一起討論賽道騎乘技巧，又在今年為MotoGP同廠隊隊友，一起在賽道上競速，可以稱呼其兩人為“爆走兄弟”，成為賽道上十足的話題性。\n\n\n\n\n\n"),
    Riders(Name:"Miguel Oliveira-米格爾·奧利維拉",Bikenumber:"88",Championships:"0",Team:"Red Bull KTM Tech 3",Manufacturers: "KTM",Age: "25",Nationality: "葡萄牙Portuguese",Activeyears: "(2019~至今)",Introduction: "       葡萄牙世界摩托車錦標賽的摩托車手，2015年在Moto3世界錦標賽上獲得亞軍，也在2018年Moto2世界錦標賽上獲得亞軍。\n\n     在2015年意大利大獎賽上，奧利維拉（Oliveira）贏得了葡萄牙車手的第一次分站冠軍。\n\n       奧利維拉（Oliveira）的父親是一名前摩托車賽車手，他一向支持兒子的賽車運動，並在他四歲時給了他第一次四輪摩托車。他從9歲開始參加全國冠軍賽，2004年參加了葡萄牙MiniGP冠軍賽，獲得了葡萄牙年度最佳諾言獎。\n\n      他的第一個成功是在2005年，當時他贏得了葡萄牙Portuguese MiniGP championship和西班牙Metrakit World Festival 。\n\n     在2006年，他再次獲得了先前的成功，並在2007年贏得了地中海PreGP 125獎杯。\n\n        2009年，他在西班牙錦標賽中排名第三，並在2010年與馬維里克·維那勒斯（Maverick Viñales）爭奪冠軍，最終僅以2分的成績獲得亞軍，並逐漸成為第一個邁向世界冠軍的正式葡萄牙車手。\n\n       目前仍在MotoGP適應且持續努力。\n\n\n\n\n\n")
    
    
]


let Circuit=[
    CircuitData(GPName:"卡達站",circuitName:"Losail International Circuit-羅賽爾國際賽車場",Fastlaptimes:"Yamaha YZR-M1(2019)/Maverick Viñales/1:53:54",Introduction:"羅賽爾國際賽車場是一條位於波斯灣卡達杜哈郊區的賽道。\n\n卡達位於阿拉伯半島。\n\n此賽道於2004年開放使用，以短短不到一年的時間，聘請1000位工人，花費5800萬美元的成本建造完畢。\n\n首次賽事為萬寶路MotoGP卡達站，冠軍為塞特吉伯諾 (Sete Gibernau)。\n\n此外，此賽道舉辦了2006年的大師賽，由尼格爾·曼塞爾(Nigel Mansell)贏得冠軍。\n\n此賽道的長度為5.380公里，賽道大直線僅有1068公尺。周圍種以人工草皮，避免太多沙塵覆蓋賽道路面。\n\n2007年，賽車場針對夜賽增加了戶外照明設備。\n\n在當時，由馬斯科照明公司所建造的羅賽爾賽道是世界上最大規模的照明設施。\n\n目前這項殊榮屬於另一個波斯灣的賽車場，阿布達比的Yas Marina賽車場。在MotoGP歷史上首場夜賽為2008年3月在此舉行。\n\n2009年2月，GP2亞洲系列賽在此舉辦夜賽。最快單圈為尼古拉斯·賀根堡的1'35.741。\n\n此賽道有10個右彎，6個左彎。6號是全場最低速的彎道，與10號彎道皆為雙Apex點的設計。\n\n目前最快圈速為Maverick Viñales以1:53.54締造的成績。\n\n\n"),
    CircuitData(GPName:"泰國站",circuitName:"Chang International Circuit-武里南國際賽車場",Fastlaptimes:"Yamaha YZR-M1(2019)/Fabio Quartararo/ 1:29:72",Introduction:"Chang國際賽車場，又因地名稱為武里南國際賽車場，位於泰國武里南。\n\n其賽道開放於2014年，這是泰國第一條FIA(國際汽車聯盟) 1級賽事和FIM(國際摩托車賽車協會) A級賽事。\n\n主要舉辦賽事有MotoGP、超級GT、SBK(世界超級摩托車錦標賽)、WTCC(世界房車錦標賽)\n\n其賽道長度為4.554 公里 (2.830英里)，總共有12個彎道\n\n在2015年正式開始WTCC(世界房車錦標賽)等汽車高級賽事，另外也開始SBK(世界超級摩托車錦標賽)第一項摩托車賽事。\n\n近年於2017年9月正式宣佈在武里南賽車場將舉行MotoGP等賽事，並確實納入每年MotoGP其中的分站，目前以舉行3年的賽事，其命名為'PTT泰國大獎賽'。\n\n\n"),
    CircuitData(GPName:"美洲站",circuitName:"Circuit of the Americas-美洲賽道",Fastlaptimes:"Honda RC213V(2017)/Marc Marquez/2:02:74",Introduction:"是一座位於美國德克薩斯州特拉維斯縣的賽車場，靠近州首府奧斯汀市邊界。\n\n該賽道現為一級方程式錦標賽（F1）美國大獎賽的舉辦場地，此外還舉辦世界耐力錦標賽、世界摩托車錦標賽等賽事的分站賽。\n\n賽道長度5.513公里（3.427英里），總共20個彎道。\n\n賽道和大獎賽是在2010年中期首次提出的。賽道是美國第一個為一級方程式專門建造的賽道。\n\n從2012年正式開放比賽，首先登場的就是F1賽車，而MotoGP則是2013年才進入本賽車場競賽。\n\n其賽車場有建立瞭望台、圓形劇場、大廣場，使得許多活動、演唱會、橄欖球比賽都曾在這裡舉辦。\n\n\n"),
    CircuitData(GPName:"阿根廷站",circuitName:"Autódromo Termas de Río Hondo-特瑪斯賽道",Fastlaptimes:"Honda RC213V(2019)/Marc Marquez/1:38:30",Introduction:"位於阿根廷-特馬斯德里奧翁多，根據意大利賽道設計師Jarno Zaffelli所設計，該賽道於2007年創建，並於2012年進行了完整的大修復和重建過程。\n\n目前舉辦的賽事有MotoGP、WTCC(世界房車錦標賽)、Super TC2000。\n\n賽道全長4.80公里 / 2.99 英里，總共14個彎道，雖然彎道較少，卻有極具挑戰的的大直線，可供賽車較勁速度的極限。\n\n\n"),
    
    CircuitData(GPName:"西班牙站",circuitName:"Circuito de Jerez-赫雷斯-安赫爾·涅托賽道",Fastlaptimes:"Yamaha YZR-M1(2019)/Fabio Quartararo/1:36:88",Introduction:"舊稱為赫雷斯賽道和赫雷斯永久賽道（西班牙語：Circuito Permanente de Jerez），是位於西班牙安達魯西亞赫雷斯-德拉弗龍特拉近郊的一條長4.428公里（2.752英里）的賽道，總共13個彎道。\n\n賽道歷史，2013年5月2日的消息指出，最後一號彎將以西班牙摩托車錦標賽世界冠軍豪爾赫·洛倫佐之名命名。\n\n2018年5月3日，賽道更名，以紀念2017年去世的前摩托車手ÁngelNieto。\n\n賽道於1985年12月8日開放。1986年，賽道於3月在西班牙舉辦了第一場國際摩托車賽事，4月在西班牙舉行了一級方程式 大獎賽。\n\n目前舉辦的賽事有一級方程式賽車(F1)、MotoGP、歐洲賽車大獎賽\n\n夏熱的地中海氣候，具有明顯的乾旱炎熱夏季及溫和多雨的冬季。\n\n目前在五月初舉行的MotoGP賽事降低了降雨的風險，並且可能將平均氣溫提高了幾度。\n\n\n"),
    CircuitData(GPName:"法國站",circuitName:"Le Mans (Bugatti) Circuit-利曼/布加迪賽道",Fastlaptimes:"Yamaha YZR-M1(2016)/Johann Zarco/1:31:18",Introduction:"首先必須提到-薩爾特賽道，又名24小時賽道，通常也稱為利曼賽道，位於法國薩爾特省利曼，是著名的利曼24小時耐力賽舉辦地。賽道全長13.629公里，是世界上最長的賽道之一。\n\n薩爾特賽道是一條半永久賽道：只有包含發車直道在內的一小部分屬於永久賽道（稱為布加迪賽道），其餘部分均由公共道路組成，僅在比賽及官方測試時段作為賽道使用。\n\n賽道以直道為主，賽車在比賽中85%的時間為全油門行駛。\n\n其中最長的穆桑直道（Mulsanne Straight）長達6公里，在1988年曾有賽車比賽中在直道達到時速405公里的歷史紀錄。\n\n出於安全考慮，1990年穆桑直道添加了兩個減速彎以降低車速。目前利曼原型車在直道上的極速可達345.6 km/h，單圈平均速度可達245 km/h。\n\n而MotoGP賽事的賽道布加迪賽道是位於薩爾特賽道”內側“的永久賽道，與後者共享發車直道等路段，其餘部分為專門建造。賽道因紀念布加迪汽車公司創始人埃托雷·布加迪而得名。賽道目前舉辦世界摩托車錦標賽法國大獎賽、利曼24小時摩托車耐力賽等賽事，並曾在1967年舉辦F1法國大獎賽。\n\n\n"),
    CircuitData(GPName:"義大利站",circuitName:"Autodromo Internazionale del Mugello -穆杰羅賽道",Fastlaptimes:"Honda RC213V(2019)/Marc Marquez/1:45:52",Introduction:"位於義大利托斯卡納，賽道長度是5.245公里（3.259英里），有14個轉彎和一條長直道（1.141公里）。\n\n賽道旁的體育場看台可容納50,000人。\n\n此外，德國房車大師賽每年舉行一次。賽道是Scuderia Ferrari（法拉利車隊)的財產，將其用於一級方程式賽車測試。A1大獎賽-2008/09的賽季的第一場比賽原本計劃於2008年9月21日在穆杰羅Mugello賽車場舉行。但是，由於建造新賽車的新底盤的時間推遲，該比賽不得不取消。\n\n\n"),
    CircuitData(GPName:"加泰隆尼亞站",circuitName:"Circuit de Barcelona-Catalunya -加泰隆尼亞賽道",Fastlaptimes:"Honda RC213V(2019)/Marc Marquez/1:40:507",Introduction:"又稱巴塞隆納賽道，是一條位於西班牙加泰隆尼亞自治區巴塞隆納的賽道，全長4.655公里（2.892英里），總共16個彎道，看台可以容納10.7萬名觀眾，於1991年啟用。\n\n該賽道由數條長直道和多種彎道組成，能夠全面地考驗賽車的性能。在此舉辦的賽事有世界一級方程式錦標賽、世界摩托車錦標賽、國際汽聯GT錦標賽等等。\n\n這個著名的賽道在 1996年西班牙F1大獎賽上，舒馬赫在大雨中奪得了他在法拉利車隊的首個冠軍。\n\n在最初啟用的幾年間，在這條賽道上很容易超車。車手可以在最後兩個彎角接近對手，並利用尾流在接下來的彎道上完成超越。但隨著賽車空氣動力學設計的改變，這樣的超車策略逐漸變得難以實現。因為領先的賽車可以在尾部產生一定的擾亂氣流，從而使得其他賽車難以緊跟其後。\n\n加泰隆尼亞賽道同時承辦了其他多項賽事，這其中包括世界摩托車錦標賽。對摩托車手而言，第1、2、4、10、14號彎角都是適合超車的地方。\n\n\n"),
    CircuitData(GPName:"德國站",circuitName:"Circuit de Barcelona-Catalunya -薩克森靈賽道",Fastlaptimes:"Honda RC213V(2019)/Marc Marquez/1:20:19",Introduction:"位於德國-薩克森，賽道長度3.700公里（2.299英里），總共14個彎道。建築師為赫爾曼·蒂爾克，最早從1927年至1990年就舉行過賽事，接下來有年的封閉賽道，經過改建後，於1996年重新開放， 目前賽道能容納超過12萬人。\n\n在當前的事件中，特別是在業餘愛好中，嚴格的音量(噪音)限制始終是一個問題，但摩托車世界冠軍賽等賽事將獲得豁免。\n\n2018年，為紀念德國賽車手拉爾夫·瓦爾德曼（Ralf Waldmann），第11號彎重新命名為拉爾夫·瓦爾德曼（Ralf-Waldmann）彎道。\n\n\n"),
    CircuitData(GPName:"荷蘭站",circuitName:"TT Circuit Assen -亞森賽道",Fastlaptimes:"Yamaha YZR-M1(2019)/Fabio Quartararo/1:32:02",Introduction:"艾森賽道是賽車 賽道建於1955年，位於荷蘭-亞森。荷蘭TT的主要賽場，它被這項運動的愛好者普遍稱為“ 摩托車大教堂”。 \n\n自1949年舉辦該系列賽事以來，該場地保持著每年唯一舉辦格蘭披治摩托車賽事的記錄。\n\n可容納110,000名觀眾，包括60,000 個座位。\n\n自1992年以來，該賽道也已成為超級摩托車世界錦標賽(SBK)賽程的一部分。\n\n總長度為4.545公里（2.824英里），總共有21個彎道，主要彎道分別為右:12，左:6。\n\n亞森賽車場建於1955年，最初的長度為7.705公里。混合了直線和大幅度的慢轉彎。最長的直線是560公尺（0.348英里）。\n\n亞森（Assen ）的彎道傳統上是傾斜的，並且表面非常具有抓地力，因此車手在賽道上的行駛速度比其他賽道快得多。如今，由於安全問題，已經對這些傾斜或彎曲的彎頭進行了修改。\n\n創新：2004年7月6日，該組織宣布了在賽道以北建立一個遊樂園的計劃。2006年，北部環路被拆除，長度縮短至4.545公里。新中心預計將接待30萬人，總投資約為8500萬歐元。\n\n\n"),
    CircuitData(GPName:"芬蘭站",circuitName:"KymiRing-屈米/伊蒂賽道",Fastlaptimes:"尚無資料",Introduction:"於今年正式加入MotoGP賽事，賽道長度4.6公里（2.86英里），是一條近年建設完成的賽道，位於芬蘭屈米河谷區伊蒂，與區首府科沃拉接壤，位於首都赫爾辛基東北110公里（68英里）處。\n\n該賽道建成後，將成為芬蘭第一條擁有國際汽車聯合會1級執照的賽道。\n\n它計劃將舉辦世界摩托車錦標賽芬蘭大獎賽，在34年的缺席後將於2019年重返賽程。由於擁有1級執照，儘管舉辦一級方程式大獎賽最初被認為過於昂貴屈米賽道將能夠舉辦任何國際汽聯准許的比賽，例如一級方程式賽車。\n\n\n"),
    CircuitData(GPName:"捷克站",circuitName:"Brno Circuit-布爾諾賽道",Fastlaptimes:"Honda RC213V(2016)/Marc Marquez/1:54:60",Introduction:"亦可稱之為馬薩里克賽道，座落於捷克共和國-布爾諾。\n\n最初的賽道由公共道路組成，最長的路程為18英里（29公里）。在1930年代，諸如Masaryk大獎賽之類等賽事吸引了頂級車隊和車手。\n\n這條賽道由第一任總統捷克斯洛伐克，托馬什馬薩里克的名字命名。在1986年之後，新的（當前）賽道開通，在舊賽道上的比賽宣告結束\n\nMotoGP它自1950年以來就在這裡舉行，是捷克共和國最著名的賽車比賽。自1965年以來，一直是世界大獎賽的一部分。\n\n賽道全長為5.403公里（3.357英里），總共14個彎道右彎:8、左彎6。\n\n\n"),
    CircuitData(GPName:"奧地利站",circuitName:"Red Bull Ring-紅牛賽道",Fastlaptimes:"    Honda RC213V (2019)/Marc Marquez/1:23:03",Introduction:"是位於奧地利施泰爾斯皮爾堡的一條賽道。\n\n賽道長度4.326公里（2.688英里），總共10個彎道。\n\n這條賽道建立初為奧地利賽道並從1970年至1987年連續18年舉辦一級方程式奧地利大獎賽。在這之後，經過重建、縮短並且重新命名為A1賽道，從1997年到2003年再次舉辦奧地利大獎賽。\n\n當一級方程式要再回歸這條賽道時，提出了一個擴大賽道布局的計畫。賽道的部分被拆除，其中包括維修站及主看台，但是工程停擺，賽道依然數年無法使用，一直到紅牛的迪特利希·馬特希茨買下並且重建，重新命名為紅牛賽道並於2011年5月15日重啟使用，之後便舉辦一季的2011年德國房車賽與2011年二級方程式冠軍賽，而一級方程式將會於2014年賽季重返。\n\n 舊的奧地利賽道常被指其位於較廣為人知的策爾特韋格，但是這條賽道重未經過移址，儘是修改過而已。此外，策爾特韋格機場賽道只舉辦過唯一的1964年奧地利大獎賽，因此得知了這個名字。\n\n\n"),
    CircuitData(GPName:"英國站",circuitName:"Silverstone Circuit-銀石賽道",Fastlaptimes:"Honda RC213V (2019)/Marc Marquez/1:58:17",Introduction:"是英格蘭的賽車場，毗鄰北安普敦郡 （Samplestone）和惠特伯里（Whittlebury）的村莊。\n\n賽道長度5.891公里（3.661英里），總共18個彎道。\n\n銀石賽道位於第二次世界大戰 皇家空軍轟炸機基地，皇家空軍銀石轟炸機基地，該基地於1943年啟用。基地是第17作戰訓練部隊的基地。該機場的三條跑道，以經典的第二次世界大戰三角形格式，位於當前跑道的輪廓內。\n\n銀石賽道是1948年英國大獎賽的舉辦地。1950年當時新設立的MotoGP英國大獎賽也將銀石賽道作為第一場比賽。\n\n\n"),
    CircuitData(GPName:"聖馬利諾站",circuitName:"Misano World Circuit Marco Simoncelli-馬爾科·西蒙切利賽道",Fastlaptimes:"Ducati GP18/Jorge Lorenzo/1:31:63",Introduction:"位於義大利-里米尼省，它最初設計於1969年，全長3.488公里（2.17英里），於1972年舉辦了第一屆賽事。1993年，賽道長度增加到4.064公里（2.53英里）。\n\n從2007年開始，它作為MotoGP世界錦標賽的賽道開始舉辦聖馬力諾和里米尼海岸大獎賽。2012年，賽道改名以紀念2011年去世的當地摩托車手Marco Simoncelli。\n\n為了再次舉辦世界摩托車錦標賽，2006年對賽道進行了大規模修改。賽道方向改為順時針方向，賽道長度增加到4.180公里（2.597英里），賽道寬度擴大到14 m（46英尺），設施得到改善，並且所有安全措施均已應用。修改後的第一場MotoGP比賽是2007年聖馬力諾和里米尼海岸大獎賽，這是由“主場”車廠'杜卡迪'所贏得的。\n\n\n"),
    CircuitData(GPName:"亞拉岡站",circuitName:"Motorland Aragon-亞拉岡賽道",Fastlaptimes:"Ducati GP18/Jorge Lorenzo/1:46:88",Introduction:"位於西班牙的阿爾卡尼伊斯，是一條長達5.078公里的摩托車賽道，總共16個彎道。\n\n這條賽道是由知名的德國建築師赫爾曼·提爾克與英國的建築公司福斯特建築事務所合力打造。一級方程式賽車車手兼法拉利試車手佩德羅·德·拉·羅薩則擔任這項計畫的技術與運動顧問。\n\n該設施的設計包括三個主要區域，運動區和休閒與文化區。該技術園將設有與汽車行業相關的研究和教育機構，運動區將包括賽車道（具有多種賽道安排），卡丁車賽道和各種碎石道，而休閒和文化區將設有酒店，商務中心和購物設施。\n\n\n"),
    CircuitData(GPName:"日本站",circuitName:"Twin Ring Motegi-雙環茂木賽道",Fastlaptimes:"Yamaha YZR-M1(2016)/Valentino Rossi/1:43:95",Introduction:"位於日本櫪木縣，芳賀郡茂木町，1997年 8 月開始營業。茂木賽道是舉行四輪SUPER GT和MotoGP日本大獎賽（或太平洋大獎賽）的地方。也經常舉行日本的國內賽車比賽。\n\n賽道長度為4.800公里（2.983英里），共有14個彎道。\n\n名稱來自具有兩條跑道的設施：橢圓形2.493公里（1.549英里）和4.8公里（2.98英里）的賽道。\n\n賽道是本田公司於1997年建造的，是該公司將印地賽車系列帶到日本努力的一部分，有助於增加他們對美國敞篷賽車的了解。\n\n目前，它是一個休閒度假勝地，除了賽道外還有遊樂園和酒店。\n\n\n"),
    CircuitData(GPName:"澳洲站",circuitName:"Phillip Island Grand Prix Circuit-菲利浦島大獎賽道",Fastlaptimes:"Yamaha YZR-M1(2019)/Maverick Viñales/1:28:49",Introduction:"位於澳大利亞-維多利亞省-菲利浦島，此賽道於1956年首次使用。\n\n賽道長度為4.445公里 (2.762 英里)，總共有12個彎道。\n\n菲利普島的賽車運動始於1928年的100英里公路比賽，此後成為第一次澳大利亞大獎賽。\n\n當時賽道利用局部封閉的公共道路的高速矩形和四個相似的右彎角。路線長度各不相同，汽車路線每圈約6英里（9.7公里），而摩托車賽道的長度約為10英里（16公里）。這條舊賽道一直是直到1935年澳大利亞大獎賽的比賽場地，最後一次在1935年5月6日舉行了禧年日比賽。\n\n1988年至今，賽道進行了整修，縮短後的長度為4.445公里，並於1988年12月4日重新開放，以進行1988年斯旺國際摩托車保險系列的最後一輪比賽。\n\n\n"),
    CircuitData(GPName:"馬來西亞站",circuitName:"Sepang International Circuit-雪邦國際賽道",Fastlaptimes:"Yamaha YZR-M1(2019)/Fabio Quartararo/1:58:30",Introduction:"是位於馬來西亞雪蘭莪州雪邦的一座動力運動賽車場，十分臨近同樣位於雪邦的吉隆坡國際機場。雪邦國際賽道承辦的主要賽事包括從1999至2017年舉辦的一級方程式賽車馬來西亞大獎賽、世界摩托車錦標賽馬來西亞大獎賽等、馬來西亞默迪卡耐力賽等。\n\n賽道長度為    5.543公里（3.445英里），共有15個彎道。\n\n雪邦賽道以其漂亮的賽車道、維修站、媒體中心和主看台而著名。但是也有人批評其賽道表面凹凸不平，而且賽道有微微下沉之勢。這有可能與雪邦賽道是建在沼澤地上的原因有關。\n\n賽道是由著名的德國設計師'赫爾曼·蒂爾克'設計，他後來還設計了上海國際賽車場、巴林國際賽道、伊斯坦堡賽道、華倫西亞賽道、濱海灣市街賽道、亞斯碼頭賽道、韓國國際賽道、佛陀國際賽道、美洲賽道等。\n\n這個賽道由馬來西亞第四任首相敦馬哈迪於1999年3月7日2030時（東八區）正式宣布啟用，並在同年4月20日和10月17日為世界摩托車錦標賽和一級方程式賽車馬來西亞大獎賽開幕。\n\n主賽道通常以順時針方向進行比賽，全長約為5.543公里，以大彎道和寬直道著名。\n\n它的賽道布局也很不尋常，有一個非常長的非常緊的927米長的髮夾彎。\n\n此外，雪邦賽道還可以以另外的方式舉行比賽。主賽道的北半部能獨立使用，順時針方向，全長2.71公里。它的南半部同樣能單獨舉行比賽，順時針方向，全長2.61公里。雪邦賽道也設有卡丁車和摩托車越野設施。\n\n\n"),
    CircuitData(GPName:"瓦倫西亞站",circuitName:"Comunitat Valenciana Ricardo Tormo-里卡多·托爾莫賽道",Fastlaptimes:"Yamaha YZR-M1(2016)/Jorge Lorenzo/1:29:40",Introduction:"又稱為里卡多·托莫賽道，位於西班牙-瓦倫西亞-切斯特，建立於1999年。\n\n賽道全長4.005公里 (2.488 英里)，總共14個彎道。\n\n此賽道計劃至少繼續舉辦到2021年的世界摩托車錦標賽賽事瓦倫西亞大獎賽。它可容納165,000名觀眾，其中125,000名觀眾席位，並以瓦倫西亞摩托車冠軍里卡多·托莫（Ricardo Tormo）的名字命名，兩次獲得50cc世界冠軍。\n\n鑑於歐洲冬季氣候溫和，許多歐洲賽車運動和摩托車隊在季前賽期間都使用賽道進行測試。賽道還有曾舉行鐵人兩項和自行車比賽。\n\n自2002年以來，這條賽道一直是MotoGP年度賽事最後一場比賽的舞台-最終站瓦倫西亞。\n\n\n")
    
    
]

let Item=[
    ManufacturerItem (Name:"Yamaha YZR-M1(2019)",Introduction:"Motorcycle type:Sport\n\n製造年份:2019 - 2019\n\n製造發源地:Japan\n\n引擎型號:直列四缸引擎\n\n排氣量:1000 cc\n\n變速器:6個檔位\nLogo主要贊助商:Monster Energy魔爪能量飲料\n\n\n"),
    ManufacturerItem (Name:"Ducati GP19",Introduction:"Motorcycle type:Sport\n\n製造年份:2019 - 2019\n\n製造發源地:Italy\n\n引擎型號:L型四缸引擎\n\n排氣量:1000 cc\n\n變速器:6個檔位\nLogo主要贊助商:Mission Winnow(菲利普莫里斯國際公司-菸草公司)\n\n\n"),
    ManufacturerItem (Name:"KTM RC16 (2019)",Introduction:"Motorcycle type:Sport\n\n製造年份:2019 - 2019\n\n製造發源地:Austria\n\n引擎型號:V型四缸引擎\n\n排氣量:1000 cc\n\n變速器:6個檔位\nLogo主要贊助商:Red Bull紅牛能量飲料\n\n\n"),
    ManufacturerItem (Name:"Aprilia RS-GP (2019)",Introduction:"Motorcycle type:Sport\n\n製造年份:2019 - 2019\n\n製造發源地:Italy\n\n引擎型號:V型四缸引擎\n\n排氣量:1000 cc\n\n變速器:6個檔位\nLogo主要贊助商:Sky Q(歐洲衛星廣播公司)\n\n\n"),
    ManufacturerItem (Name:"Honda RC213V (2019)",Introduction:"Motorcycle type:Sport\n\n製造年份:2019 - 2019\n\n製造發源地:Japan\n\n引擎型號:V型四缸引擎\n\n排氣量:1000 cc\n\n變速器:6個檔位\nLogo主要贊助商:REPSOL力豹仕機油(西班牙石油公司)\n\n\n"),
    ManufacturerItem (Name:"Suzuki GSX-RR (2019)",Introduction:"Motorcycle type:Sport\n\n製造年份:2019 - 2019\n\n製造發源地:Japan\n\n引擎型號:直列四缸引擎\n\n排氣量:1000 cc\n\n變速器:6個檔位\nLogo主要贊助商:ECSTAR機油(Suzuki鈴木自家機油及贊助商)\n\n\n")
]
